FROM node:22-alpine AS build
WORKDIR /app
RUN corepack enable
COPY src/frontend/ETOmniverse.Web/package.json ./
RUN pnpm install
COPY src/frontend/ETOmniverse.Web/ ./
RUN pnpm run build

FROM nginx:1.27-alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
