FROM node:22-alpine AS build
WORKDIR /app
COPY src/frontend/ETOmniverse.Web/package*.json ./
RUN npm install
COPY src/frontend/ETOmniverse.Web/ ./
RUN npm run build

FROM nginx:1.27-alpine AS final
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
