"""
Regenerate the ADR summary table in docs/DECISIONS.md from docs/decisions/D-*.md frontmatter.

Modes:
  python scripts/build-adr-index.py            # rewrite docs/DECISIONS.md in place
  python scripts/build-adr-index.py --check    # dry-run, exit 1 if drift detected (CI use)

Markers (must exist in docs/DECISIONS.md):
  <!-- BEGIN AUTO-GENERATED ADR INDEX -->
  ...
  <!-- END AUTO-GENERATED ADR INDEX -->
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ADR_DIR = REPO_ROOT / "docs" / "decisions"
SUMMARY_FILE = REPO_ROOT / "docs" / "DECISIONS.md"

BEGIN_MARKER = "<!-- BEGIN AUTO-GENERATED ADR INDEX -->"
END_MARKER = "<!-- END AUTO-GENERATED ADR INDEX -->"

EXCLUDE_NAMES = {"_template.md", "README.md"}


def parse_frontmatter(text: str) -> dict[str, str] | None:
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n", text, re.DOTALL)
    if not m:
        return None
    fm: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        fm[key.strip()] = val.strip()
    return fm


def numeric_id(adr_id: str) -> int:
    m = re.match(r"D-?(\d+)", adr_id)
    return int(m.group(1)) if m else 0


def collect_adrs() -> list[dict[str, str]]:
    if not ADR_DIR.exists():
        return []
    adrs = []
    for path in sorted(ADR_DIR.glob("D-*.md")):
        if path.name in EXCLUDE_NAMES:
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if fm is None:
            print(f"WARN  no frontmatter: {path.name}", file=sys.stderr)
            continue
        adrs.append({
            "id": fm.get("id", ""),
            "title": fm.get("title", ""),
            "status": fm.get("status", ""),
            "date": fm.get("date", ""),
            "supersedes": fm.get("supersedes", ""),
            "superseded_by": fm.get("superseded-by", ""),
            "filename": path.name,
        })
    adrs.sort(key=lambda a: numeric_id(a["id"]))
    return adrs


def render_table(adrs: list[dict[str, str]]) -> str:
    if not adrs:
        return "_(尚無 ADR — 待規劃期 D10-D18 搬入 `docs/decisions/D-*.md` 後此表自動產出)_"
    lines = ["| ID | 日期 | 狀態 | 決策 | 鏈結 |", "|---|---|---|---|---|"]
    for a in adrs:
        chain_parts = []
        if a["supersedes"]:
            chain_parts.append(f"supersedes {a['supersedes']}")
        if a["superseded_by"]:
            chain_parts.append(f"superseded-by {a['superseded_by']}")
        chain = "; ".join(chain_parts) or "—"
        link = f"[{a['id']}](decisions/{a['filename']})"
        lines.append(f"| {link} | {a['date']} | {a['status']} | {a['title']} | {chain} |")
    return "\n".join(lines)


def replace_block(text: str, new_inner: str) -> str | None:
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(text):
        return None
    return pattern.sub(f"{BEGIN_MARKER}\n{new_inner}\n{END_MARKER}", text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="dry-run, exit 1 if drift detected (for CI)",
    )
    args = parser.parse_args()

    if not SUMMARY_FILE.exists():
        print(f"ERR  {SUMMARY_FILE} not found", file=sys.stderr)
        return 1

    text = SUMMARY_FILE.read_text(encoding="utf-8")
    if BEGIN_MARKER not in text or END_MARKER not in text:
        print(
            f"ERR  markers missing in {SUMMARY_FILE.name}.\n"
            f"     add this block where the ADR table should be:\n\n"
            f"     {BEGIN_MARKER}\n"
            f"     <auto-generated content>\n"
            f"     {END_MARKER}",
            file=sys.stderr,
        )
        return 1

    adrs = collect_adrs()
    table = render_table(adrs)
    new_text = replace_block(text, table)

    if new_text == text:
        print(f"OK   ADR index up to date ({len(adrs)} ADR{'s' if len(adrs) != 1 else ''})")
        return 0

    if args.check:
        print(
            "ERR  ADR index drift detected.\n"
            "     run: python scripts/build-adr-index.py",
            file=sys.stderr,
        )
        return 1

    SUMMARY_FILE.write_text(new_text, encoding="utf-8")
    print(f"OK   wrote {SUMMARY_FILE.name} ({len(adrs)} ADR{'s' if len(adrs) != 1 else ''})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
